### ISSUE TITLE
Test issue

### ISSUE THREAD

**Issue by okeefem** [rdpstaff/ReadSeq#1]
Testing notifications

**Comment by wangqion** [comment]
This is a test reply.

On Fri, Feb 20, 2015 at 11:00 AM, okeefem <notifications@github.com> wrote:

> Closed #1 <https://github.com/rdpstaff/ReadSeq/issues/1>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rdpstaff/ReadSeq/issues/1#event-239210120>.
>



-- 
Qiong
